export const FETCH_GET_ALBUM_LIST_REQUEST = 'FETCH_GET_ALBUM_LIST_REQUEST';
export const FETCH_GET_ALBUM_LIST_SUCCESS = 'FETCH_GET_ALBUM_LIST_SUCCESS';
export const FETCH_GET_ALBUM_LIST_FAILURE = 'FETCH_GET_ALBUM_LIST_FAILURE';
export const FETCH_GET_AUTH_REQUEST = 'FETCH_GET_AUTH_REQUEST';
export const FETCH_GET_AUTH_SUCCESS = 'FETCH_GET_AUTH_SUCCESS';
export const FETCH_GET_AUTH_FAILURE = 'FETCH_GET_AUTH_FAILURE';
